apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tmks
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ltmq-tenant/rhtap-demo-app/hacbs-test-project-tmks@sha256:eb1aaea7baa118b498deb41276e7fd273fc0359f9e72bbff645706b1a780e5e6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
