apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tmks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tmks
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-tmks
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tmks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tmks
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ltmq-tenant/rhtap-demo-app/hacbs-test-project-tmks@sha256:eb1aaea7baa118b498deb41276e7fd273fc0359f9e72bbff645706b1a780e5e6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
